### ISSUE TITLE
Fix doc.rs

### ISSUE THREAD

**Issue by Yamakaky** [CasualX/vigem-client#1]
I think it's because docs.rs defaults to linux target. See https://docs.rs/about/metadata

**Comment by CasualX** [comment]
Hey, thanks for opening an issue!

It looks like I already have a fix in place in master branch, but it is not yet published. This is because it also includes an optimization attempt to reuse event objects instead of constantly creating them. I have not been able to properly test if this resource optimization works correctly.

I have a project which I'll try to verify that this new code is still correct and publish afterwards.

**Comment by Yamakaky** [comment]
Nice!

**Comment by CasualX** [comment]
fixed
